### ISSUE TITLE
Fork 404

### ISSUE THREAD

**Issue by jakebrady5** [learn-co-curriculum/rack-dynamic-web-apps#1]
Fork lab link is 404, don't see a suitable repo to manually fork

**Comment by jakebrady5** [comment]
for Dynamic Web Apps With Rack

**Comment by AnnJohn** [comment]
Hi @jakebrady5 sorry for the issue that you're having? Could you please report this as a bug and/or use the Ask a Question tool within Learn to resolve the issue? Thanks
