### ISSUE TITLE
unable to fork this lab on IDE

### ISSUE THREAD

**Issue by tahseen447** [learn-co-curriculum/rack-dynamic-web-apps#4]

**Comment by sgharms** [comment]
Hi there! This request sounds like an improvement to the Learn platform.
[Raising issues on GitHub][raise] should be reserved for problems with the
curriculum itself (doesn't work, throws a Ruby error, etc.)

Our product team loves to hear about our Learners' innovative interface
improvements. You can reach them at support@learn.co. Alternatively, if Learn
is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try
to discern a proper path to resolution.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
